server:
  port: "80"

db:
  username: "feedback_app"
  host: "db"
  port: "5432"
  dbname: "feedback_app"
  sslmode: "disable"

memcache:
  host: "memcached"
  port: "11211"

kafka:
  host: "broker:29092"